<?php

//Creamos una base variable con la base de datos para crearla sino existe
$sqlBaseDatos = "
CREATE DATABASE IF NOT EXISTS COFRADIA  ;
USE COFRADIA;

CREATE TABLE IF NOT EXISTS COFRADIA.USUARIO(
    id_usu INT AUTO_INCREMENT NOT NULL,
    DNI VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    Nomb_usu VARCHAR(50) NOT NULL,
    Ape_usu VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    poblacion VARCHAR(100) NOT NULL,
    cod_postal INT NOT NULL,
    provincia VARCHAR(100),
    CONSTRAINT usuario_PK PRIMARY KEY (id_usu),
    CONSTRAINT usuario_UQ1 UNIQUE (DNI),
    CONSTRAINT usuario_UQ2 UNIQUE (email)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS COFRADIA.TIPO(
    id_tipo INT AUTO_INCREMENT,
    Nomb_tipo VARCHAR (50) NOT NULL,
    Descrip_tipo VARCHAR (150),
    CONSTRAINT tipo_PK PRIMARY KEY (id_tipo),
    CONSTRAINT tipo_UQ UNIQUE(Nomb_tipo)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS COFRADIA.OPERACIONES(
    id_ope INT AUTO_INCREMENT,
    Nomb_ope VARCHAR (50) NOT NULL,
    Descrip_ope VARCHAR (150),
    CONSTRAINT operaciones_PK PRIMARY KEY (id_ope),
    CONSTRAINT operaciones_UQ UNIQUE(Nomb_ope)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS COFRADIA.PERTENECEN(
    id_usu INT NOT NULL,
    id_tipo INT NOT NULL,
    CONSTRAINT pertenecen_PK1 PRIMARY KEY (id_usu,id_tipo),
    CONSTRAINT pertenecen_FK1 FOREIGN KEY (id_usu) REFERENCES COFRADIA.USUARIO (id_usu) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT pertenecen_FK2 FOREIGN KEY (id_tipo) REFERENCES COFRADIA.TIPO(id_tipo) ON DELETE ?????RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB;
    
CREATE TABLE IF NOT EXISTS COFRADIA.REALIZAN(
    id_ope INT NOT NULL,
    id_tipo INT NOT NULL,
    CONSTRAINT realizan_PK1 PRIMARY KEY (id_ope,id_tipo),
    CONSTRAINT realizan_FK1 FOREIGN KEY (id_ope) REFERENCES COFRADIA.OPOERACIONES (id_ope) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT realizan_FK2 FOREIGN KEY (id_tipo) REFERENCES COFRADIA.TIPO(id_tipo) ON DELETE ??????RESTRICT ON UPDATE CASCADE) ENGINE=InnoDB;";


?>
